[package]
name = "trast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
onnxruntime = { version = "0.0.14", features = ["model-fetching"] }
tokenizers = "0.13.2"
