name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - id: prep
        working-directory: ./trast
        run: |
          echo ::set-output name=version::$(cargo pkgid | cut -d "#" -f2 -)
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/akeamc/trast:${{ steps.prep.outputs.version }}
            ghcr.io/akeamc/trast:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
